# See https://containers.dev/guide/dockerfile for the Dockerfile format
FROM mcr.microsoft.com/devcontainers/javascript-node:1-20-bullseye

# Install rsvg-convert
RUN apt-get update && apt-get install -y librsvg2-bin graphviz

# Install Java (OpenJDK 11)
RUN apt-get install -y openjdk-11-jdk