@startuml
sprite $clarity [48x48/16] {
000000000027BEFFFFFFFFFFFFFFFFFFFFDB720000000000
000000004CFFFFFFFFFFFFFFFFFFFFFFFFFFFFC400000000
0000002CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC2000000
000004FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF500000
00006FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF60000
0004FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4000
002FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF200
00BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB00
04FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF40
0CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC0
2FFFFFFFFFFFFFFFA52AFFFFA52BFFFFA52BFFFFFFFFFFF2
7FFFFFFFFFFFFFD20009FFC2000AFFC2000AFFFFFFFFFFF6
AFFFFFFFFFFFFE10037CFE10037DFE10038DFFFFFFFFFFFA
DFFFFFFFFFFFF6008FFFF5009FFFF500AFFFFFFFFFFFFFFD
EFFFFFFFFFFFF004FFFFE005FFFFE005FFFFFFFFFFFFFFFE
FFFFFFFFFFFFC00AFFFFB00BFFFFB00BFFFFFFFFFFFFFFFF
FFFFFFFFFFFFB00DFFFF900EFFFF900EFFFFFFFFFFFFFFFF
FFFFFFFFFFFFA00EFFFF900FFFFF900EFFFFFFFFFFFFFFFF
FFFFFFFFFFFFA00EFFFF900FFFFF900EFFFFFFFFFFFFFFFF
FFFFFFFFFFFFA00EFFFF900FFFFF900EFFFFFFFFFFFFFFFF
FFFFFFFFFFFFA00EFFFF900FFFFF900EFFFFFFFFFFFFFFFF
FFFFFFFFFFFFA00EFFFF900FFFFF900EFFFFFFFFFFFFFFFF
FFFFFFFFFFFFA00EFFFF900FFFFF900EFFFFFFFFFFFFFFFF
FFFFFFFFFFFFA00EFFFF900FFFFF900EFFFFFFFFFFFFFFFF
FFFFFFFFFFFFA00EFFFF900FFFFF900EFFFFFFFFFFFFFFFF
FFFFFFFFFFFFA00EFFFF900FFFFF900EFFFFFFFFFFFFFFFF
FFFFFFFFFFFFA00EFFFF900FFFFF900EFFFFFFFFFFFFFFFF
FFFFFFFFFFFFA00EFFFF900FFFFF900EFFFFFFFFFFFFFFFF
FFFFFFFFFFFFA00EFFFF900FFFFF900EFFFFFFFFFFFFFFFF
FFFFFFFFFFFFA00EFFFF900FFFFF900EFFFFFFFFFFFFFFFF
FFFFFFFFFFFFB00EFFFF900FFFFF900EFFFFFFFFFFFFFFFF
FFFFFFFFFFFFB00DFFFF900EFFFF900DFFFFFFFFFFFFFFFF
FFFFFFFFFFFFC00AFFFFB00BFFFFB00AFFFFFFFFFFFFFFFF
EFFFFFFFFFFFF104FFFFE004FFFFF004FFFFFFFFFFFFFFFE
DFFFFFFFFFFFF7008FFFF5009FFFF6008FFFFFFFFFFFFFFD
AFFFFFFFFFFFFF20038CFE10038DFE20038DFFFFFFFFFFFA
7FFFFFFFFFFFFFD30008FFD20009FFD30008FFFFFFFFFFF6
2FFFFFFFFFFFFFFFB539FFFFA53AFFFFB539FFFFFFFFFFF2
0CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC0
04FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF40
00BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB00
002FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE200
0004FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4000
00006FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF60000
000004FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF400000
0000002CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB2000000
000000004CFFFFFFFFFFFFFFFFFFFFFFFFFFFFC400000000
000000000027BDFFFFFFFFFFFFFFFFFFFFDB620000000000
}


!define DEV2_CLARITY(_alias) ENTITY(rectangle,black,clarity,_alias,DEV2 CLARITY)
!define DEV2_CLARITY(_alias, _label) ENTITY(rectangle,black,clarity,_label, _alias,DEV2 CLARITY)
!define DEV2_CLARITY(_alias, _label, _shape) ENTITY(_shape,black,clarity,_label, _alias,DEV2 CLARITY)
!define DEV2_CLARITY(_alias, _label, _shape, _color) ENTITY(_shape,_color,clarity,_label, _alias,DEV2 CLARITY)
skinparam folderBackgroundColor<<DEV2 CLARITY>> White
@enduml