@startuml
sprite $rstudio [48x48/16] {
00000000000000000159BDEFFEDB95100000000000000000
0000000000000016CFFFFFFFFFFFFFFC6100000000000000
00000000000019FFFFFFFFFFFFFFFFFFFF81000000000000
000000000006FFFFFFFFFFFFFFFFFFFFFFFF800000000000
0000000002DFFFFFFFFFFFFFFFFFFFFFFFFFFC2000000000
000000005FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF500000000
00000006FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF60000000
0000006FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6000000
000005FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF500000
00002FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF20000
0000DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC0000
0007FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7000
001FFFFFFFFFFFF9467764221249EFFFFFFFFFFFFFFFF100
009FFFFFFFFFFFF80000000000001AFFFFFFFFFFFFFFF800
01FFFFFFFFFFFFFFEC402CCDDB8100BFFFFFFFFFFFFFFF10
06FFFFFFFFFFFFFFFF604FFFFFFD002FFFFFFFFFFFFFFF60
0CFFFFFFFFFFFFFFFF604FFFFFFF800DFFFFFFFFFFFFFFC0
1FFFFFFFFFFFFFFFFF604FFFFFFFD00BFFFFFFFFFFFFFFF1
5FFFFFFFFFFFFFFFFF604FFFFFFFD00CFFFFFFFFFFFFFFF5
9FFFFFFFFFFFFFFFFF604FFFFFFF600FFFFFFFFFFFFFFFF8
BFFFFFFFFFFFFFFFFF604FFFFFF8006FFFFFFFFFFFFFFFFB
DFFFFFFFFFFFFFFFFF603CCCB93002FFFFFFFFFFFFFFFFFD
EFFFFFFFFFFFFFFFFF60000000006FFFFFFFFFFFFFFFFFFE
FFFFFFFFFFFFFFFFFF600333002EFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF603FFF900AFFFFFFFFFFFFFFFFFFFF
EFFFFFFFFFFFFFFFFF603FFFF401EFFFFFFFFFFFFFFFFFFE
DFFFFFFFFFFFFFFFFF603FFFFE005FFFFFFFFFFFFFFFFFFD
BFFFFFFFFFFFFFFFFF603FFFFF900AFFFFFFFFFFFFFFFFFB
9FFFFFFFFFFFFFFFFF603FFFFFF401EFFFFFFFFFFFFFFFF8
5FFFFFFFFFFFFFFFFF603FFFFFFE106FFFFFFFFFFFFFFFF5
1FFFFFFFFFFFFFFFFF603FFFFFFF900BFFFFFFFFFFFFFFF1
0CFFFFFFFFFFFFFC88301888EFFFF40199BFFFFFFFFFFFC0
06FFFFFFFFFFFFF800000000DFFFFE10004FFFFFFFFFFF60
01FFFFFFFFFFFFFB55555555EFFFFFA5558FFFFFFFFFFF10
009FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF800
001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF100
0007FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7000
0000DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC0000
00002FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF20000
000005FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF500000
0000006FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6000000
00000006FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF60000000
000000005FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF500000000
0000000002CFFFFFFFFFFFFFFFFFFFFFFFFFFC2000000000
000000000006FFFFFFFFFFFFFFFFFFFFFFFF800000000000
00000000000018FFFFFFFFFFFFFFFFFFFF81000000000000
0000000000000016CFFFFFFFFFFFFFFC6100000000000000
00000000000000000158BDEFFEDB85100000000000000000
}


!define DEV2_RSTUDIO(_alias) ENTITY(rectangle,black,rstudio,_alias,DEV2 RSTUDIO)
!define DEV2_RSTUDIO(_alias, _label) ENTITY(rectangle,black,rstudio,_label, _alias,DEV2 RSTUDIO)
!define DEV2_RSTUDIO(_alias, _label, _shape) ENTITY(_shape,black,rstudio,_label, _alias,DEV2 RSTUDIO)
!define DEV2_RSTUDIO(_alias, _label, _shape, _color) ENTITY(_shape,_color,rstudio,_label, _alias,DEV2 RSTUDIO)
skinparam folderBackgroundColor<<DEV2 RSTUDIO>> White
@enduml