@startuml
sprite $vuestorefront [48x48/16] {
000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000
00000004BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA00000000
00000009FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF20000000
00000ADFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD400000
00000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF900000
00001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA00000
00002FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC00000
00003FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE00000
00005FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
00006FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF10000
00007FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF20000
00009FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF30000
0000AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF50000
0000BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF60000
0000CFFFFFFFFFFFFFFFFFFFFFFFFFFD8FFFFFFFFFF70000
0000EFFFFFFFFFFFFFFFFFFFFFFFFFD104FFFFFFFFF80000
0000FFFFFFFFFFFFFFFFFFFFFFFFFD16E24FFFFFFFFA0000
0000FFFFFFFFFFFFFFFFFFFFFFFFD16FFD14FFFFFFFB0000
0002FFFFFFFFF9DFFFFFFFFFFFFFB6FE8FD5FFFFFFFC0000
0003FFFFFFFFF38FFFFFFFFFFFFFFFFA1FFFFFFFFFFE0000
0004FFFFFFFFF46FFFFFFFFFFFFFFFF82FFFFFFFFFFF0000
0005FFFFFFFFF64FFFFFFFFFFFFFFFF65FFFFFFFFFFF0000
0007FFFFFFFFFA1FFFFFFFFFFFFFFFF28FFFFFFFFFFF2000
0008FFFFFFFFFE0BFFFFFFFFFFFFFFD0DFFFFFFFFFFF3000
0009FFFFFFFFFF54FFFFFFFFFFFFFF63FFFFFFFFFFFF4000
000BFFFFFFFFFFD0BFFFFFFFFFFFFC0BFFFFFFFFFFFF6000
000CFFFFFFFFFFF71EFFFFFFFFFFE25FFFFFFFFFFFFF7000
000DFFFFFFFFFFFF42EFFFFFFFFE22FFFFFFFFFFFFFF8000
000EFFFFFFFFFFFFF41AFFFFFFA13EFFFFFFFFFFFFFFA000
000FFFFFFFFFFFFFFF8016896107FFFFFFFFFFFFFFFFB000
001FFFFFFFFFFFFFFFFE963358EFFFFFFFFFFFFFFFFFC000
002FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE000
004FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000
005FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000
006FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF200
007FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF300
009FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF400
00AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF600
00BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF700
00CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF900
00EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB00
00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC00
009CCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDD600
000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000
}


!define DEV2_VUESTOREFRONT(_alias) ENTITY(rectangle,black,vuestorefront,_alias,DEV2 VUESTOREFRONT)
!define DEV2_VUESTOREFRONT(_alias, _label) ENTITY(rectangle,black,vuestorefront,_label, _alias,DEV2 VUESTOREFRONT)
!define DEV2_VUESTOREFRONT(_alias, _label, _shape) ENTITY(_shape,black,vuestorefront,_label, _alias,DEV2 VUESTOREFRONT)
!define DEV2_VUESTOREFRONT(_alias, _label, _shape, _color) ENTITY(_shape,_color,vuestorefront,_label, _alias,DEV2 VUESTOREFRONT)
skinparam folderBackgroundColor<<DEV2 VUESTOREFRONT>> White
@enduml